local function desc(new)
   describe("functionality",function()
      local eq = function(a,b) return assert.is_equal(b,a) end
      it("new() to not error",new)
      it("read(number) to work correctly",function()
         local s = new("abc")
         s:seek("set",0)
         eq(s:read(3),"abc")
      end)
      it("new(content) to set content",function()
         local s = new("abcdef_ghi")
         s:seek("set",0)
         eq(s:read(10),"abcdef_ghi")
      end)
      it("read('*a') to work correctly",function()
         local s = new("edfghijkl")
         s:seek("set",0)
         eq(s:read("*a"),"edfghijkl")
      end)
      it("read('*l') to work correctly",function()
         local s = new("abc\ndef")
         s:seek("set",0)
         eq(s:read("*l"),"abc")
         eq(s:read("*l"),"def")
      end)
      --[[not_it("read('*n') to work",function()
      new():read("*n")
      end)]]
      it("seek() to return correct positions",function()
         local s = new("abcdef\nghijkl")
         eq(s:seek("cur"),13)
         eq(s:seek("set",1),1)
         eq(s:seek("end"),13)
         s:close()
      end)
      it("seek() to set correct positions",function()
         local s = new("abcdef\nghijkl") -- #s == 13
         eq(s:seek("set",5),5)
         eq(s:seek("cur",-3),2)
         eq(s:seek("cur",4),6)
         eq(s:seek("end",-3),10)
         s:close()
      end)
      it("write() to update the pointer",function()
         local s = new("aaabbb")
         s:seek("set",0)
         s:write('abc')
         eq(s:seek("cur"),3)
         s:close()
      end)
      it("write() to change stream contents",function()
         local s = new("Aaabbb")
         s:seek("set",0)
         s:write("aaa")
         s:seek("set",0)
         eq(s:read("*a"),"aaabbb")
         s:seek("end",-3)
         s:write("ccc")
         s:seek("set",0)
         eq(s:read("*a"),"aaaccc")
         s:close()
      end)
   end)
end
describe("io's stream",function()
   desc(function(content)
      local f = io.tmpfile()
      if content then f:write(content) end
      return f
   end)
end)
describe("lua-based stream",function()
   desc(require('stream').factory.new)
end)